### ISSUE TITLE
Generic Commands?

### ISSUE THREAD

**Issue by wongcain** [groupon/grox#39]
I am curious why Command does not make use of generics like Action does.  Wouldn't it be better to define Command like this?

```
public interface Command<STATE> {
  Observable<? extends Action<STATE> actions();
}
```

**Comment by stephanenicolas** [comment]
It sounds to me, but I don't remember why we didn't do it this way... We should definitely give it a try. Do you wanna do a PR @wongcain ?

**Comment by wongcain** [comment]
Thanks @stephanenicolas. PR submitted.

**Comment by wongcain** [comment]
Oops. My change broke the samples and now I see why it probably implemented this way... the generic prevents you from using the `Observable.cast()` function to support the success vs error Action emissions.  I've updated my PR to do the casting in the `map()` function instead.  I personally like this approach better, but I understand if prefer you prefer the non-generic Command version.  It's easy enough to make use of my own generic version of Command instead of the library.

**Comment by alin-turcu** [comment]
It's easy enough to make use of my own generic version of Command instead of the library. 
@wongcain can you explain why would you use your versions of command instead of the ones in the library? We would be happy to make it better

**Comment by wongcain** [comment]
Well I have been trying to make use of them in Kotlin and have been running into type-safety issues since `store.dispatch` is expecting a typed action and `Command` is emitting a generic one. I admit that my issue may be due to the limits of my understanding of generics and/or Kotlin,

Take this example from your project:
`clicks(button)
            .map(click -> new RefreshColorCommand())
            .flatMap(RefreshColorCommand::actions)
            .subscribe(store::dispatch, this::doLog)`

The only way I've figured out how to implement that line in Kotlin is with an unchecked cast on the Action:
`                clicks(button)
                        .map { click -> RefreshColorCommand() }
                        .flatMap<Action<*>>({ it.actions() })
                        .subscribe(
                                { store.dispatch(it as Action<State>?) },
                                { this.doLog(it) })`

But using my version of Command with generics, the cast is unnecessary:
`                clicks(button)
                        .map { click -> RefreshColorCommand() }
                        .flatMap<Action<State>>({ it.actions() })
                        .subscribe({ store.dispatch(it) }, { this.doLog(it) })`

It also gives me piece of mind that there is a contract in place for each command to only emit Actions of a single state-type.

**Comment by chenthorne** [comment]
We've ended up doing the same because of our use of grox in Kotlin. Typing the Command and action observable it returns makes the Kotlin compiler happy and since we don't use the `.cast()` operator we don't have any issues from that. We can still do error actions using `.onErrorResumeNext`

```
interface Command<STATE> {
    fun actions(): Observable<out Action<STATE>>
}
```

and an example implementation:

```
return api.makeApiCall(argument)
            .map { result -> SuccessResultAction(result) }
            .onErrorResumeNext({ t: Throwable -> Observable.just(ErrorAction(t))})
```

**Comment by alin-turcu** [comment]
@chenthorne https://github.com/groupon/grox/pull/40 what do you think? We are currently testing this approach in our app also.

**Comment by chenthorne** [comment]
Any update on merging PR #40 ?

**Comment by alin-turcu** [comment]
@chenthorne Waiting for QA green light on this and our first release with the new update. We wanna make sure it works for us before releasing into the wild

**Comment by mradzinski** [comment]
I was about to avoid using Grox due to this issue being open, until I realized Grox 1.1.2 implements the changes mentioned here. Any reason why this is still open @alin-turcu? 🙂

**Comment by alin-turcu** [comment]
@mradzinski thanks. I forgot about it. Closing it now
