### ISSUE TITLE
core-rx and core-rx2 have class name collision when used in same project

### ISSUE THREAD

**Issue by chenthorne** [groupon/grox#42]
Surprising as it may sound, I have a project with RxJava1/Grox Rx1 in one module, and RxJava2/Grox Rx2 in another. They work fine on their own, but when bringing them together, there's a collision as `grox-core-rx` and `grox-core-rx2` use the same package and class name.

Most libraries solve this evolution problem by namespacing the Rx related classes under `rx1` or `rx2`. Would this be something Grox would be willing to support?

**Comment by chenthorne** [comment]
@alin-turcu any idea when this will be available in a release?

**Comment by alin-turcu** [comment]
@chenthorne Grox 1.1.2 has been released
